# Generated by Django 3.2 on 2021-05-04 12:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 5, 4, 12, 44, 8, 749665, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='questions',
            field=models.CharField(max_length=200),
        ),
    ]
